import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import MainLayout from "@/components/layouts/main";
import AnimatePresenceLayout from "@/components/animate-presence";
import { dmSans, inter } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={[dmSans.variable, inter.variable].join(" ")}>
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <MainLayout>
            <AnimatePresenceLayout>{children}</AnimatePresenceLayout>
          </MainLayout>
        </ThemeProvider>
      </body>
    </html>
  );
}
