import type { Metadata } from "next";
import "./globals.css";
import { dmSans, inter } from "@/lib/fonts";
import Body from "./body";
import { HamburgerContextProvider } from "@/context/hamberger-state";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={[dmSans.variable, inter.variable].join(" ")}>
      <HamburgerContextProvider>
        <Body>{children}</Body>
      </HamburgerContextProvider>
    </html>
  );
}
