import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "../globals.css";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { cn } from "@/lib/utils";
import Footer from "@/components/footer";
import { Navbar } from "@/components/nav";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/lib/i18n/routing";
import { notFound } from "next/navigation";
import { Playfair, Gabarito } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const playfair = Playfair({
  subsets: ["latin"],
  variable: "--font-playfair",
});

const mPlusRounded = Gabarito({
  subsets: ["latin"],
  variable: "--font-m-plus-rounded",
});

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <>
      <html lang={locale} suppressHydrationWarning>
        <head />
        <body
          className={cn(
            GeistSans.variable,
            GeistMono.variable,
            playfair.variable,
            mPlusRounded.variable
          )}
        >
          <NextIntlClientProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="relative flex-auto min-w-0 flex flex-col mt-2 md:mt-8 mb-12">
                <Navbar />
                <div className="px-6 sm:px-4 md:px-0 max-w-[650px] mx-auto w-full">
                  {children}
                  <Footer />
                </div>
              </main>
            </ThemeProvider>
          </NextIntlClientProvider>
        </body>
      </html>
    </>
  );
}
